import { Metadata } from "next";
import DashboardHeader from "./DashboardHeader";


export const metadata: Metadata = {
    title: "login",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <div className="flex flex-1 flex-col ">
            {/* Top Header */}
            <DashboardHeader />

            {/* Page Content */}
            <div className="flex-1 overflow-y-auto p-4">
                {children}
            </div>
        </div>

    );
}
